"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const apiRoutes_1 = __importDefault(require("./apiRoutes"));
const authRoutes_1 = __importDefault(require("./authRoutes"));
const bulkMessageRoutes_1 = __importDefault(require("./bulkMessageRoutes"));
const chatBotRoutes_1 = __importDefault(require("./chatBotRoutes"));
const contactRoutes_1 = __importDefault(require("./contactRoutes"));
const messageRoutes_1 = __importDefault(require("./messageRoutes"));
const queueRoutes_1 = __importDefault(require("./queueRoutes"));
const quickAnswerRoutes_1 = __importDefault(require("./quickAnswerRoutes"));
const scheduleRoutes_1 = __importDefault(require("./scheduleRoutes"));
const settingMessageRoutes_1 = __importDefault(require("./settingMessageRoutes"));
const settingRoutes_1 = __importDefault(require("./settingRoutes"));
const tagRoutes_1 = __importDefault(require("./tagRoutes"));
const ticketRoutes_1 = __importDefault(require("./ticketRoutes"));
const userRoutes_1 = __importDefault(require("./userRoutes"));
const webHookRoutes_1 = __importDefault(require("./webHookRoutes"));
const whatsappRoutes_1 = __importDefault(require("./whatsappRoutes"));
const whatsappSessionRoutes_1 = __importDefault(require("./whatsappSessionRoutes"));
const routes = (0, express_1.Router)();
routes.use(userRoutes_1.default);
routes.use("/auth", authRoutes_1.default);
routes.use(settingRoutes_1.default);
routes.use(contactRoutes_1.default);
routes.use(ticketRoutes_1.default);
routes.use(whatsappRoutes_1.default);
routes.use(messageRoutes_1.default);
routes.use(whatsappSessionRoutes_1.default);
routes.use(queueRoutes_1.default);
routes.use(quickAnswerRoutes_1.default);
routes.use(chatBotRoutes_1.default);
routes.use(scheduleRoutes_1.default);
routes.use(tagRoutes_1.default);
routes.use("/webhook", webHookRoutes_1.default);
routes.use("/api/messages", apiRoutes_1.default);
routes.use("/bulkMessage", bulkMessageRoutes_1.default);
routes.use(settingMessageRoutes_1.default);
exports.default = routes;
